# Generated by Django 4.2.30 on 2026-08-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('project_type', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, default='Rameshwaram, Tamil Nadu', max_length=200)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1-5')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
