# Generated by Django 4.2.30 on 2026-08-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('project_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Interior', 'Interior'), ('Renovation', 'Renovation'), ('Turnkey', 'Turnkey')], default='Residential', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('budget', models.CharField(blank=True, max_length=120)),
                ('project_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('In Progress', 'In Progress'), ('Converted', 'Converted'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('assigned_manager', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
